In [4]:
import torch

loss = torch.nn.MSELoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
print(input.shape, target.shape)
output = loss(input, target)
output.backward()
print(output.shape)

torch.Size([3, 5]) torch.Size([3, 5])
torch.Size([])


In [2]:
import numpy as np
r = {"key1": np.array([1, 2, 3]), "key2": np.array([4, 5, 6])}
m = np.array([[]])
for id, key in enumerate(r):
    print(id, key)
# Beispiel: Zwei Arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])  # Neue Spalte

# Mit column_stack
result = np.column_stack((a, b))

# Mit concatenate (axis=1)
result2 = np.concatenate((a, b), axis=1)

print(result)
print(result2)

0 key1
1 key2
[[1 2 5]
 [3 4 6]]
[[1 2 5]
 [3 4 6]]
